# PBL Advances in AI
# Prankur Rana, Sushrut Khajuria
# MTEG220034, MTEG220017

# <center> Water Quality Prediction</center>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,roc_curve,accuracy_score, classification_report

In [4]:
df_raw = pd.read_csv(r"C:\Users\91700\Desktop\water_potability.csv")
df_raw

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
...,...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,47580.991603,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1
3272,7.808856,193.553212,17329.802160,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1
3273,9.419510,175.762646,33155.578218,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1
3274,5.126763,230.603758,11983.869376,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1
3275,7.874671,195.102299,17404.177061,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1

In [14]:
#Generates the descriptive statistics which includes - mean,  standard deviation, etc.
df_raw.describe()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
count,2785.000000,3276.000000,3276.000000,3276.000000,2495.000000,3276.000000,3276.000000,3114.000000,3276.000000,3276.000000
mean,7.080795,196.369496,22014.092526,7.122277,333.775777,426.205111,14.284970,66.396293,3.966786,0.390110
std,1.594320,32.879761,8768.570828,1.583085,41.416840,80.824064,3.308162,16.175008,0.780382,0.487849
min,0.000000,47.432000,320.942611,0.352000,129.000000,181.483754,2.200000,0.738000,1.450000,0.000000
25%,6.093092,176.850538,15666.690297,6.127421,307.699498,365.734414,12.065801,55.844536,3.439711,0.000000
50%,7.036752,196.967627,20927.833607,7.130299,333.073546,421.884968,14.218338,66.622485,3.955028,0.000000
75%,8.062066,216.667456,27332.762127,8.114887,359.950170,481.792304,16.557652,77.337473,4.500320,1.000000
max,14.000000,323.124000,61227.196008,13.127000,481.030642,753.342620,28.300000,124.000000,6.739000,1.000000

In [15]:
#Checking Missing Values
def fill_nan(df):
    for index, column in enumerate(df.columns[:9]):
        # print(index, column)
        df[column] = df[column].fillna(df.groupby('Potability')[column].transform('mean'))
    return df
        
df = fill_nan(df_raw)
df.isna().sum()  
df.describe()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
count,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000
mean,7.080855,196.369496,22014.092526,7.122277,333.785123,426.205111,14.284970,66.395671,3.966786,0.390110
std,1.469958,32.879761,8768.570828,1.583085,36.145701,80.824064,3.308162,15.769901,0.780382,0.487849
min,0.000000,47.432000,320.942611,0.352000,129.000000,181.483754,2.200000,0.738000,1.450000,0.000000
25%,6.277673,176.850538,15666.690297,6.127421,317.094638,365.734414,12.065801,56.647656,3.439711,0.000000
50%,7.085378,196.967627,20927.833607,7.130299,334.564290,421.884968,14.218338,66.303555,3.955028,0.000000
75%,7.870050,216.667456,27332.762127,8.114887,350.385756,481.792304,16.557652,76.666609,4.500320,1.000000
max,14.000000,323.124000,61227.196008,13.127000,481.030642,753.342620,28.300000,124.000000,6.739000,1.000000

In [16]:
scaler = MinMaxScaler()
array = scaler.fit_transform(df.to_numpy())
df2 = pd.DataFrame(array, columns = ['ph','Hardness','Solids','Cloramines', 'Sulphate', 'Conductivity', 'Organic_carbon', 'Trihalomethanes','Turbidity', 'Potability'])
df2.describe()

,ph,Hardness,Solids,Cloramines,Sulphate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
count,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000
mean,0.505775,0.540231,0.356173,0.529963,0.581725,0.427940,0.463026,0.532668,0.475853,0.390110
std,0.104997,0.119263,0.143968,0.123921,0.102678,0.141336,0.126750,0.127938,0.147548,0.487849
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.448405,0.469432,0.251957,0.452088,0.534313,0.322196,0.378000,0.453584,0.376198,0.000000
50%,0.506098,0.542401,0.338338,0.530591,0.583939,0.420386,0.460473,0.531920,0.473630,0.000000
75%,0.562146,0.613857,0.443498,0.607662,0.628882,0.525145,0.550102,0.615994,0.576729,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [17]:
def PCA_manual(X , num_components):
     
    #Step-1
    X_meaned = X - np.mean(X , axis = 0)
     
    #Step-2
    cov_mat = np.cov(X_meaned , rowvar = False)
     
    #Step-3
    eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)
     
    #Step-4
    sorted_index = np.argsort(eigen_values)[::-1]
    sorted_eigenvalue = eigen_values[sorted_index]
    sorted_eigenvectors = eigen_vectors[:,sorted_index]
     
    #Step-5
    eigenvector_subset = sorted_eigenvectors[:,0:num_components]
     
    #Step-6
    X_reduced = np.dot(eigenvector_subset.transpose() , X_meaned.transpose() ).transpose()
     
    return X_reduced

In [18]:
#prepare the data
X = df2.drop(['Potability'], axis = 1)
y = df2['Potability']
 
#Applying it to PCA function
mat_reduced = PCA_manual(X , 5)
 
#Creating a Pandas DataFrame of reduced Dataset
df_scratch = pd.DataFrame(mat_reduced , columns = ['PC1','PC2','PC3','PC4','PC5'])
 
#Concat it with target variable to create a complete Dataset
df_scratch = pd.concat([df_scratch , pd.DataFrame(y)] , axis = 1)

df_scratch.head(5)

        PC1       PC2       PC3       PC4       PC5  Potability
0  0.143044 -0.126447 -0.221423 -0.215436 -0.080040         0.0
1 -0.133792  0.021579 -0.293855  0.018233 -0.052341         0.0
2  0.191367 -0.056504  0.002839  0.026840  0.062097         0.0
3 -0.025501  0.105893  0.081274 -0.139060  0.307606         0.0
4  0.006565  0.073069  0.032842  0.196886 -0.213541         0.0

In [20]:
pca = PCA(n_components=5)
pca.fit(X)
mat = pca.transform(X)
df_built_in = pd.DataFrame(mat, columns = ['PC1','PC2','PC3','PC4','PC5'])
df_built_in = pd.concat([df_built_in , pd.DataFrame(y)] , axis = 1)
print(df_built_in)

           PC1       PC2       PC3       PC4       PC5  Potability
0    -0.143044  0.126447  0.221423 -0.215436 -0.080040         0.0
1     0.133792 -0.021579  0.293855  0.018233 -0.052341         0.0
2    -0.191367  0.056504 -0.002839  0.026840  0.062097         0.0
3     0.025501 -0.105893 -0.081274 -0.139060  0.307606         0.0
4    -0.006565 -0.073069 -0.032842  0.196886 -0.213541         0.0
...        ...       ...       ...       ...       ...         ...
3271  0.352370  0.267780  0.064626 -0.051113 -0.030461         1.0
3272 -0.243637  0.081858 -0.024819  0.089647  0.158538         1.0
3273  0.005933  0.194635 -0.036193 -0.092634 -0.093243         1.0
3274  0.014635 -0.210118 -0.017748 -0.095881 -0.037434         1.0
3275 -0.323683  0.116297 -0.149412 -0.041036  0.092275         1.0

[3276 rows x 6 columns]

In [22]:
#Dividing dataset into traing and testing set with 30-70 ratio 
#Dropping last column (output)
X_scratch = df_scratch.drop(['Potability'], axis = 1)
y_scratch = df_scratch['Potability']

X_built_in = df_built_in.drop(['Potability'], axis = 1)
y_built_in = df_built_in['Potability']

# Splitting
X_train_scratch, X_test_scratch, y_train_scratch, y_test_scratch = train_test_split(X_scratch,y_scratch, test_size=0.3, random_state=1111, stratify=y_scratch) #stratify=y
X_train_built_in, X_test_built_in, y_train_built_in, y_test_built_in = train_test_split(X_built_in,y_built_in, test_size=0.3, random_state=1111, stratify=y_built_in) #stratify=y

In [24]:
#KNN 
from sklearn.neighbors import KNeighborsClassifier 

k = range(1,20,1)
testing_accuracy_scratch = []
training_accuracy_scratch = []

testing_accuracy_built_in = []
training_accuracy_built_in = []
score = 0

#scratch
for i in k:
    knn= KNeighborsClassifier(n_neighbors=i, metric='minkowski', p=3 )  
    knn.fit(X_train_scratch, y_train_scratch)  
    y_pred_train = knn.predict(X_train_scratch)
    training_accuracy_scratch.append(accuracy_score(y_train_scratch, y_pred_train))
    
    y_pred_test = knn.predict(X_test_scratch)
    acc_score = accuracy_score(y_test_scratch,y_pred_test)
    testing_accuracy_scratch.append(acc_score)
    
    if score < acc_score:
        score = acc_score
        best_k = i
        
print('Best Accuracy Score for PCA from scratch', score, 'Best K-Score', best_k)

#Built_in
for i in k:
    knn= KNeighborsClassifier(n_neighbors=i, metric='minkowski', p=3 )  
    knn.fit(X_train_built_in, y_train_built_in)  
    y_pred_train = knn.predict(X_train_built_in)
    training_accuracy_built_in.append(accuracy_score(y_train_built_in, y_pred_train))
    
    y_pred_test = knn.predict(X_test_built_in)
    acc_score = accuracy_score(y_test_built_in,y_pred_test)
    testing_accuracy_built_in.append(acc_score)
    if score < acc_score:
        score = acc_score
        best_k = i

print('Best Accuracy Score for PCA from built -in', score, 'Best K-Score', best_k)

Best Accuracy Score for PCA from scratch 0.6063072227873856 Best K-Score 2
Best Accuracy Score for PCA from built -in 0.6063072227873856 Best K-Score 2